"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlparse, parse_qs
import logging
from logging.handlers import TimedRotatingFileHandler



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Simple .env loader (no external dependency) ---
def _load_dotenv(env_path: Path) -> None:
    try:
        if env_path.exists():
            for line in env_path.read_text(encoding='utf-8').splitlines():
                line = line.strip()
                if not line or line.startswith('#'):
                    continue
                if '=' not in line:
                    continue
                k, v = line.split('=', 1)
                k = k.strip()
                v = v.strip().strip('"').strip("'")
                # Do not override already-set environment variables
                os.environ.setdefault(k, v)
    except Exception:
        # Fail-safe: ignore .env errors
        pass

# Load project-level .env from repository root (BASE_DIR is backend/, parent is repo root)
# Determine environment mode
MODE = os.environ.get("MODE", "local")

# Load the appropriate .env file
if MODE == "production":
    _load_dotenv(BASE_DIR.parent / ".env.production")
else:
    _load_dotenv(BASE_DIR.parent / ".env.local")



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-_5hk18dy)(=nm$%v8*swo--ddxznp0db49m$relv1%x2#ir)-w')

# SECURITY WARNING: don't run with debug turned on in production!
def _get_bool(name: str, default: bool) -> bool:
    val = os.environ.get(name)
    if val is None:
        return default
    return val.strip().lower() in {'1', 'true', 'yes', 'on'}

DEBUG = _get_bool('DJANGO_DEBUG', True)

_hosts = os.environ.get('ALLOWED_HOSTS')
if _hosts:
    ALLOWED_HOSTS = [h.strip() for h in _hosts.split(',') if h.strip()]
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',  # <--- Добавьте эту строку
    'rest_framework.authtoken',
    # Use the app config so AppConfig.ready() runs (starts in-process reminder scheduler)
    'crm_app.apps.CrmAppConfig',
    'corsheaders',
]

# In-process reminder scheduler (runs send_reminders periodically). You can override in env/local settings.
ENABLE_REMINDER_SCHEDULER = True
REMINDER_SCHEDULER_INTERVAL_SECONDS = 60  # run every 60 seconds

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # CORS should be as high as possible
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

def _parse_database_url(url: str) -> dict:
    """Minimal DATABASE_URL parser supporting Postgres.
    Examples:
    postgres://user:pass@host:port/dbname?sslmode=require
    """
    parsed = urlparse(url)
    scheme = parsed.scheme
    engine = None
    if scheme in {'postgres', 'postgresql', 'pgsql'}:
        engine = 'django.db.backends.postgresql'
    elif scheme == 'sqlite':
        engine = 'django.db.backends.sqlite3'
    else:
        raise ValueError(f"Unsupported DB scheme: {scheme}")

    if engine == 'django.db.backends.sqlite3':
        # For sqlite, allow empty path = memory or file
        name = parsed.path[1:] if parsed.path else ':memory:'
        return {
            'ENGINE': engine,
            'NAME': name or (BASE_DIR / 'db.sqlite3'),
        }

    name = parsed.path[1:] if parsed.path.startswith('/') else parsed.path
    opts = {}
    q = parse_qs(parsed.query)
    # Flatten single-value params
    for k, v in q.items():
        if v:
            opts[k] = v[0]

    db = {
        'ENGINE': engine,
        'NAME': name,
        'USER': parsed.username or '',
        'PASSWORD': parsed.password or '',
        'HOST': parsed.hostname or '',
        'PORT': str(parsed.port) if parsed.port else '',
    }
    if opts:
        # Pass sslmode and other libpq options
        db['OPTIONS'] = opts
    return db

_database_url = os.environ.get('DATABASE_URL')
# Ignore obviously placeholder URLs (e.g., contain '<' or '>') to avoid breaking local dev
if _database_url and ('<' not in _database_url and '>' not in _database_url):
    try:
        _db = _parse_database_url(_database_url)
        # If Postgres is configured but driver is missing locally, fall back to SQLite for convenience
        if _db.get('ENGINE') == 'django.db.backends.postgresql':
            try:
                import importlib  # type: ignore
                _pg_ok = False
                for _mod in ('psycopg', 'psycopg2'):
                    try:
                        importlib.import_module(_mod)
                        _pg_ok = True
                        break
                    except Exception:
                        pass
                if not _pg_ok:
                    # Driver not available -> use SQLite to allow local dev without installing drivers
                    print('[settings] psycopg/psycopg2 not found; falling back to SQLite for local development')
                    _db = {
                        'ENGINE': 'django.db.backends.sqlite3',
                        'NAME': BASE_DIR / 'db.sqlite3',
                    }
            except Exception:
                # If any error checking drivers, keep _db as is
                pass
        DATABASES = { 'default': _db }
    except Exception:
        # Fallback to sqlite if parsing fails
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Use local time zone for Poland so reminder_time comparisons match user input
TIME_ZONE = 'Europe/Warsaw'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# Where collectstatic will put built assets in container
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'crm_app.User'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '465'))
# Auto-normalize SSL/TLS: if port is 587 prefer TLS; if 465 prefer SSL unless explicitly overridden.
_env_ssl = os.getenv('EMAIL_USE_SSL')
_env_tls = os.getenv('EMAIL_USE_TLS')
if _env_ssl is not None:
    EMAIL_USE_SSL = _env_ssl.strip().lower() in {'1','true','yes','on'}
else:
    EMAIL_USE_SSL = EMAIL_PORT == 465
if _env_tls is not None:
    EMAIL_USE_TLS = _env_tls.strip().lower() in {'1','true','yes','on'}
else:
    EMAIL_USE_TLS = EMAIL_PORT in (587, 25) and not EMAIL_USE_SSL
# Avoid enabling both simultaneously
if EMAIL_USE_SSL and EMAIL_USE_TLS:
    # Prefer TLS for port 587, otherwise keep SSL
    if EMAIL_PORT == 587:
        EMAIL_USE_SSL = False
    else:
        EMAIL_USE_TLS = False
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
if DEBUG:
    print('[email] host=', EMAIL_HOST, 'port=', EMAIL_PORT, 'ssl=', EMAIL_USE_SSL, 'tls=', EMAIL_USE_TLS, 'user=', EMAIL_HOST_USER, 'from=', DEFAULT_FROM_EMAIL)
SERVER_EMAIL = DEFAULT_FROM_EMAIL
# Кто получает письма при ошибках
ADMINS = [
    ("LegalFlow Admin", "crmlegalflow@gmail.com"),
]

# --- Disable error emails in local/dev mode ---------------------------------
# If you don't want local server errors to spam admin email, we strip
# the mail_admins handler & clear ADMINS when running in DEBUG or MODE=local
if DEBUG or MODE == 'local' or os.environ.get('DISABLE_ERROR_EMAILS', '').strip().lower() in {'1','true','yes','on'}:
    ADMINS = []
    # Post-adjust LOGGING only after it's defined (will be below); we mark intent here
    _DISABLE_ERROR_EMAILS = True
else:
    _DISABLE_ERROR_EMAILS = False

# URL фронтенда (используется для генерации ссылок, например, сброс пароля)
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:8080')

# Stripe Configuration
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY', 'pk_test_51SFaGZ1dR7VpHP6keZiI7B4jKexOQpl2NhrEK4Q8oOtSbIPGmcax3pEecmPq1ZYYSKdsLc4J7duu8KW4jMUOYX2j00GpVIniO3')
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', 'sk_test_51SFaGZ1dR7VpHP6k3H3UZQM878j2rMEddzgQ5vS855oJzhq98kqxlNZvP7OS3eM6QkAmR3XEIhXbJnG1DT5E8UQQ00JLofoV1Q')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', 'whsec_b03118e7cf81451289dccb9febfc817e5fbf87c74a7ce7ed49681a9c29f23450')

_frontend_urls_env = os.environ.get('FRONTEND_URLS', '')
if _frontend_urls_env:
    _frontend_origins = [u.strip() for u in _frontend_urls_env.split(',') if u.strip()]
else:
    _frontend_origins = [FRONTEND_URL] if FRONTEND_URL else []

# When developing locally, it's convenient to allow Vue dev server origins
if DEBUG:
    for _dev in ('http://localhost:8080', 'http://127.0.0.1:8080'):
        if _dev not in _frontend_origins:
            _frontend_origins.append(_dev)

CORS_ALLOWED_ORIGINS = [
    "https://crm.legalflow.pl",
    "http://localhost",
    "http://127.0.0.1:8080",
]

# Trust the frontend origins for CSRF as well
CSRF_TRUSTED_ORIGINS = _frontend_origins

# Allow cookies/token auth over CORS if needed
CORS_ALLOW_CREDENTIALS = True

# Optional: allow all origins if explicitly requested (use only for local debugging)
if os.environ.get('CORS_ALLOW_ALL', '').strip().lower() in {'1','true','yes','on'}:
    CORS_ALLOW_ALL_ORIGINS = True

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# --- Optional S3/OVH object storage integration ---
# Enable by setting USE_S3=1 in .env.local and providing required AWS_* vars.
# Falls back silently to local media if any critical value is missing.
USE_S3 = _get_bool('USE_S3', False)
if USE_S3:
    _required_s3 = [
        'AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY', 'AWS_STORAGE_BUCKET_NAME', 'AWS_S3_ENDPOINT_URL'
    ]
    if all(os.environ.get(k) for k in _required_s3):
        try:
            # Ensure storages app present (and installed in this interpreter)
            try:
                import importlib  # type: ignore
                importlib.import_module('storages')
                if 'storages' not in INSTALLED_APPS:
                    INSTALLED_APPS.append('storages')
            except Exception as _no_st:
                # storages not installed in this environment -> fallback to local
                if DEBUG:
                    print('[storage] storages package missing in current env; falling back to local:', _no_st)
                raise RuntimeError('storages-missing')

            AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
            AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
            AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
            AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL')
            AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME') or None
            # AWS_S3_CUSTOM_DOMAIN = os.environ.get('AWS_S3_CUSTOM_DOMAIN') or ''
            # Disable custom domain to force Boto3 to sign URLs using the endpoint
            AWS_S3_CUSTOM_DOMAIN = None

            AWS_DEFAULT_ACL = os.environ.get('AWS_DEFAULT_ACL')  # let bucket policy control access by default
            # Allow override from env; default to signed URLs (True) to allow access to private objects
            # Fix: handle empty string in env as default (True)
            _qs_auth_env = os.environ.get('AWS_QUERYSTRING_AUTH')
            if _qs_auth_env is not None and _qs_auth_env.strip() != '':
                AWS_QUERYSTRING_AUTH = _qs_auth_env.strip().lower() in {'1', 'true', 'yes', 'on'}
            else:
                AWS_QUERYSTRING_AUTH = True
            
            try:
                AWS_QUERYSTRING_EXPIRE = int(os.environ.get('AWS_QUERYSTRING_EXPIRE', '3600'))
            except Exception:
                AWS_QUERYSTRING_EXPIRE = 3600
            
            # Force s3v4 signature for OVH/S3 compatibility
            AWS_S3_SIGNATURE_VERSION = os.environ.get('AWS_S3_SIGNATURE_VERSION', 's3v4')
            
            AWS_S3_FILE_OVERWRITE = False
            AWS_S3_ADDRESSING_STYLE = 'virtual'
            AWS_S3_OBJECT_PARAMETERS = {
                'CacheControl': 'max-age=86400',
                'ContentDisposition': 'inline',
            }

            # Derive MEDIA_URL
            if AWS_S3_CUSTOM_DOMAIN:
                MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN.rstrip('/')}/"
            else:
                # Path style fallback (should still work with OVH virtual hosted endpoint)
                MEDIA_URL = f"{AWS_S3_ENDPOINT_URL.rstrip('/')}/{AWS_STORAGE_BUCKET_NAME}/"

            _safe_no_delete = _get_bool('SAFE_STORAGE_NO_DELETE', False)
            if _safe_no_delete:
                _storage_backend = 'crm_app.storage.SafeS3Boto3Storage'
            else:
                _storage_backend = 'storages.backends.s3boto3.S3Boto3Storage'
            
            DEFAULT_FILE_STORAGE = _storage_backend
            STORAGES = {
                "default": {
                    "BACKEND": _storage_backend,
                },
                "staticfiles": {
                    "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
                },
            }

            if DEBUG:
                print('[storage] Using S3 storage MEDIA_URL=', MEDIA_URL, 'safe_no_delete=', _safe_no_delete)
        except Exception as _s3_err:
            if DEBUG:
                print('[storage] Failed to configure S3, falling back to local:', _s3_err)
            # Leave MEDIA_URL / MEDIA_ROOT as local
    else:
        if DEBUG:
            print('[storage] USE_S3=1 but missing required vars; using local media')


# Универсальный путь: работает и локально, и в Docker
LOG_DIR = "/app/logs" if os.path.exists("/app") else os.path.join(BASE_DIR, "logs")
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name} — {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "rotating_file": {
            "level": "DEBUG",
            "class": "logging.handlers.TimedRotatingFileHandler",
            # Use per-process log files to avoid Windows file lock issues on rotate
            "filename": os.path.join(LOG_DIR, f"legalflow.{os.getpid()}.log"),
            "when": "midnight",          # новый файл каждый день
            "backupCount": 7,            # хранить только 7 дней логов
            "encoding": "utf-8",
            "formatter": "verbose",
            # Delay file opening until first write; helps with concurrent access
            "delay": True,
        },
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
            "level": "INFO",
        },
        "mail_admins": {
            "level": "ERROR",
            "class": "django.utils.log.AdminEmailHandler",
            "include_html": True,
        },
    },
    "loggers": {
        "django": {
            "handlers": ["rotating_file", "console", "mail_admins"],
            "level": "INFO",
            "propagate": True,
        },
        "django.utils.autoreload": {
            "level": "INFO",
        },
        "django.request": {
            "handlers": ["rotating_file", "mail_admins"],
            "level": "WARNING",
            "propagate": False,
        },
        "crm_app": {
            "handlers": ["rotating_file"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["rotating_file", "console", "mail_admins"],
        "level": "INFO", 
    },
}

# Apply dynamic logging tweaks to suppress admin emails locally
try:
    if _DISABLE_ERROR_EMAILS:
        # Remove mail_admins from any handler lists if present
        for _logger_name, _logger_cfg in LOGGING.get('loggers', {}).items():
            if isinstance(_logger_cfg, dict):
                _handlers = _logger_cfg.get('handlers', [])
                if 'mail_admins' in _handlers:
                    _logger_cfg['handlers'] = [h for h in _handlers if h != 'mail_admins']
        _root_handlers = LOGGING.get('root', {}).get('handlers', [])
        if 'mail_admins' in _root_handlers:
            LOGGING['root']['handlers'] = [h for h in _root_handlers if h != 'mail_admins']
        # Keep handler definition (so Django won't error), but effectively unused
except Exception:
    pass