# Generated by Django 5.2.6 on 2025-09-22 18:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_client', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(blank=True)),
                ('passport_number', models.CharField(blank=True, max_length=20, verbose_name='Номер паспорта')),
                ('passport_expiry_date', models.DateField(blank=True, null=True, verbose_name='Срок действия паспорта')),
                ('visa_type', models.CharField(blank=True, max_length=50, verbose_name='Тип визы')),
                ('visa_expiry_date', models.DateField(blank=True, null=True, verbose_name='Срок действия визы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LegalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PREPARATION', 'Подготовка документов'), ('SUBMITTED', 'Подано'), ('IN_PROGRESS', 'На рассмотрении'), ('DECISION_POSITIVE', 'Решение положительное'), ('DECISION_NEGATIVE', 'Решение отрицательное'), ('CLOSED', 'Дело закрыто')], default='PREPARATION', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_cases', to='crm_app.client')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ZALACZNIK_1', 'Załącznik nr 1'), ('UMOWA_PRACA', 'Umowa o pracę / zlecenia'), ('UMOWA_NAJMU', 'Umowa najmu'), ('ZUS_ZUA_ZZA', 'ZUS ZUA / ZZA'), ('ZUS_RCA_DRA', 'ZUS RCA/DRA'), ('POLISA', 'Polisa ubezpieczeniowa'), ('ZASWIADCZENIE_US', 'Zaświadczenie z Urzędu Skarbowego'), ('ZASWIADCZENIA_ZUS', 'Zaświadczenia ZUS pracodawcy'), ('PIT_37', 'PIT 37'), ('BADANIE_LEKARSKIE', 'Badanie lekarskie'), ('BADANIE_MEDYCZNE', 'Badanie medyczne'), ('SWIADECTWO_KIEROWCY', 'Świadectwo kierowcy'), ('PRAWO_JAZDY', 'Prawo jazdy'), ('INNE', 'Inne')], max_length=20)),
                ('status', models.CharField(choices=[('NOT_SUBMITTED', 'Не подан'), ('SUBMITTED', 'Подан'), ('APPROVED', 'Принят'), ('REJECTED', 'Отклонен')], default='NOT_SUBMITTED', max_length=20)),
                ('legal_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm_app.legalcase')),
            ],
            options={
                'unique_together': {('legal_case', 'document_type')},
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='client_documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crm_app.document')),
            ],
        ),
    ]
