# Generated by Django 5.2.6 on 2025-09-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalcase',
            name='case_type',
            field=models.CharField(choices=[('CZASOWY_POBYT', 'ВНЖ (Карта временного побыту)'), ('STALY_POBYT', 'ПМЖ (Карта сталего побыту)'), ('REZydent_UE', 'Карта резидента ЕС'), ('OBYWATELSTWO', 'Гражданство')], default='CZASOWY_POBYT', max_length=20, verbose_name='Вид дела'),
        ),
    ]
