# Generated by Django 5.2.6 on 2025-09-21 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_alter_emailverificationtoken_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LegalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PREPARATION', 'Подготовка документов'), ('SUBMITTED', 'Подано'), ('IN_PROGRESS', 'На рассмотрении'), ('DECISION_POSITIVE', 'Решение положительное'), ('DECISION_NEGATIVE', 'Решение отрицательное'), ('CLOSED', 'Дело закрыто')], default='PREPARATION', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_cases', to='crm_app.client')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ZALACZNIK_1', 'Załącznik nr 1'), ('UMOWA_PRACA', 'Umowa o pracę / zlecenia'), ('UMOWA_NAJMU', 'Umowa najmu'), ('ZUS_ZUA_ZZA', 'ZUS ZUA / ZZA'), ('ZUS_RCA_DRA', 'ZUS RCA/DRA'), ('POLISA', 'Polisa ubezpieczeniowa'), ('ZASWIADCZENIE_US', 'Zaświadczenie z Urzędu Skarbowego'), ('ZASWIADCZENIA_ZUS', 'Zaświadczenia ZUS pracodawcy'), ('PIT_37', 'PIT 37'), ('BADANIE_LEKARSKIE', 'Badanie lekarskie'), ('SWIADECTWO_KIEROWCY', 'Świadectwo kierowcy'), ('PRAWO_JAZDY', 'Prawo jazdy'), ('INNE', 'Inne')], max_length=20)),
                ('status', models.CharField(choices=[('NOT_SUBMITTED', 'Не подан'), ('SUBMITTED', 'Подан'), ('APPROVED', 'Принят'), ('REJECTED', 'Отклонен')], default='NOT_SUBMITTED', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='client_documents/%Y/%m/')),
                ('legal_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm_app.legalcase')),
            ],
        ),
    ]
