# Generated by Django 5.2.6 on 2025-09-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_legalcase_case_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalcase',
            name='case_type',
            field=models.CharField(choices=[('-', ' -'), ('CZASOWY_POBYT', 'ВНЖ (Карта временного побыту)'), ('STALY_POBYT', 'ПМЖ (Карта сталего побыту)'), ('REZydent_UE', 'Карта резидента ЕС'), ('OBYWATELSTWO', 'Гражданство')], default='CZASOWY_POBYT', max_length=20, verbose_name='Вид дела'),
        ),
    ]
