# Generated by Django 5.2.6 on 2025-09-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_alter_legalcase_case_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalcase',
            name='status',
            field=models.CharField(choices=[('-', '-'), ('PREPARATION', 'Подготовка документов'), ('SUBMITTED', 'Подано'), ('IN_PROGRESS', 'На рассмотрении'), ('DECISION_POSITIVE', 'Решение положительное'), ('DECISION_NEGATIVE', 'Решение отрицательное'), ('CLOSED', 'Дело закрыто')], default='PREPARATION', max_length=20),
        ),
    ]
