# Generated by Django 5.2.6 on 2025-10-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_user_avatar_user_is_blocked_user_phone_user_role_and_more'),
        ('crm_app', '0004_alter_legalcase_status'),
    ]

    operations = [
    ]
