# Generated by Django 5.2.6 on 2025-10-04 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_merge_20251001_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('LEAD', 'Руководитель'), ('LAWYER', 'Юрист/Консультант'), ('MANAGER', 'Менеджер'), ('ASSISTANT', 'Ассистент')], default='LAWYER', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('LEAD', 'Руководитель'), ('LAWYER', 'Юрист/Консультант'), ('MANAGER', 'Менеджер'), ('ASSISTANT', 'Ассистент')], default='ADMIN', max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, choices=[('REMINDER', 'Напоминание'), ('SYSTEM', 'Система')], default='SYSTEM', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='crm_app.client')),
                ('reminder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='crm_app.reminder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='crm_app_not_user_id_427a07_idx'), models.Index(fields=['source'], name='crm_app_not_source_ab9ee9_idx')],
            },
        ),
    ]
