# Generated by Django 5.2.6 on 2025-10-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0009_client_notes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='crm_app_not_visible_d747d5_idx',
            old_name='crm_app_not_visible__idx',
        ),
        migrations.AddField(
            model_name='company',
            name='plan',
            field=models.CharField(default='STARTER', help_text='Код активного тарифного плана', max_length=30),
        ),
    ]
