# Generated by Django 5.2.6 on 2025-10-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0010_rename_crm_app_not_visible__idx_crm_app_not_visible_d747d5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='plan',
            field=models.CharField(default='TRIAL', help_text='Код активного тарифного плана', max_length=30),
        ),
    ]
