# Generated by Django 5.2.6 on 2025-10-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0012_alter_task_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(blank=True, choices=[('CALL', 'Звонок'), ('MEETING', 'Встреча'), ('SUBMISSION', 'Подача документов')], max_length=20),
        ),
    ]
