# Generated by Django 5.2.6 on 2025-10-16 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0014_task_created_by'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='task',
            new_name='crm_app_tas_created_a59b7a_idx',
            old_name='crm_app_task_created_by_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='crm_app.task'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['task'], name='crm_app_not_task_id_ba55cf_idx'),
        ),
    ]
