# Generated by Django 5.2.6 on 2025-11-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0019_create_permissionsets_for_remaining_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpermissionset',
            options={'verbose_name': 'Набор прав пользователя', 'verbose_name_plural': 'Наборы прав пользователей'},
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('legal_case', 'document_type', 'name')},
        ),
    ]
