# Generated by Django 5.2.6 on 2025-11-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0020_alter_userpermissionset_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
