# Generated by Django 5.2.6 on 2025-11-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0022_ensure_document_name_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='Размер файла в байтах'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('ZALACZNIK_1', 'Załącznik nr 1'), ('UMOWA_PRACA', 'Umowa o pracę / zlecenia'), ('UMOWA_NAJMU', 'Umowa najmu'), ('ZUS_ZUA_ZZA', 'ZUS ZUA / ZZA'), ('ZUS_RCA_DRA', 'ZUS RCA/DRA'), ('POLISA', 'Polisa ubezpieczeniowa'), ('ZASWIADCZENIE_US', 'Zaświadczenie z Urzędu Skarbowego'), ('ZASWIADCZENIA_ZUS', 'Zaświadczenia ZUS работадателя'), ('PIT_37', 'PIT 37'), ('BADANIE_LEKARSKIE', 'Badanie lekarskie'), ('BADANIE_MEDYCZNE', 'Badanie medyczne'), ('SWIADECTWO_KIEROWCY', 'Świadectwo kierowcy'), ('PRAWO_JAZDY', 'Prawo jazdy'), ('INNE', 'Inne')], max_length=20),
        ),
    ]
