# Generated by Django 5.2.6 on 2025-12-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0025_company_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='subscription_ends_at',
            field=models.DateTimeField(blank=True, help_text='Дата окончания текущего периода подписки', null=True),
        ),
    ]
