# Generated by Django 5.2.6 on 2025-12-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0026_company_subscription_ends_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissionset',
            name='can_manage_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
